#ifndef TASKS_COMMON_H
#define TASKS_COMMON_H

#define WIFI_APP_TASK_STACK_SIZE 4096
#define WIFI_APP_TASK_PRIORITY 5
#define WIFI_APP_TASK_CORE_ID 0

#define HTTP_SERVER_TASK_STACK_SIZE 8192
#define HTTP_SERVER_TASK_PRIORITY 4
#define HTTP_SERVER_TASK_CORE_ID 0

#define HTTP_SERVER_MONITOR_STACK_SIZE 4096
#define HTTP_SERVER_MONITOR_PRIORITY 3
#define HTTP_SERVER_MONITOR_CORE_ID 0

#define WIFI_RESET_BUTTON_TASK_STACK_SIZE 2048
#define WIFI_RESET_BUTTON_TASK_PRIORITY 6
#define WIFI_RESET_BUTTON_TASK_CORE_ID 0

#define DHT11_STACK_SIZE 4096
#define DHT11_TASK_PRIORITY 5
#define DHT11_TASK_CORE_ID 0

#define SNTP_TIME_SYNC_STACK_SIZE 4096
#define SNTP_TIME_SYNC_PRIORITY 4
#define SNTP_TIME_SYNC_CORE_ID 0

#define AWS_IOT_TASK_STACK_SIZE 9216
#define AWS_IOT_TASK_PRIORITY 6
#define AWS_IOT_TASK_CORE_ID 0

#endif
